export enum PortfolioEnums {
	TITLE = 'title',
	PORTFOLIO = 'portfolio',
	CURRENCY = 'currency',
	VALUE = 'value',
	PROFIT = 'profit',
	SPARE = 'spare',
	CHART = 'chart',
	DEAL = 'deal',
	RANGE = 'range',
	BROKER = 'broker',
	TYPE = 'type',
	STRATEGY = 'strategy',
	FILTER = 'filter',
}
