#STAGE 1
FROM node:22-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
ENV NODE_OPTIONS=--max_old_space_size=1024
RUN npm install
COPY . .
RUN npm run build
RUN echo '{"host": "https://api.grintrade.com/api", "version": '$(date +%s)'}' > /usr/src/app/dist/apps/desktop/assets/settings.json

#STAGE 2
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/apps/desktop /usr/share/nginx/html
