export enum TradeOrderTypeText {
  ORDER_TYPE_LIMIT = 'ORDER_TYPE_LIMIT',
  ORDER_TYPE_MARKET = 'ORDER_TYPE_MARKET',
  ORDER_TYPE_BESTPRICE = 'ORDER_TYPE_BESTPRICE',
}

export enum TradeStopOrderTypeText {
  STOP_ORDER_TYPE_TAKE_PROFIT = 'STOP_ORDER_TYPE_TAKE_PROFIT',
  STOP_ORDER_TYPE_STOP_LOSS = 'STOP_ORDER_TYPE_STOP_LOSS',
  STOP_ORDER_TYPE_STOP_LIMIT = 'STOP_ORDER_TYPE_STOP_LIMIT',
}

export enum TradeStopOrderExpirationType {
  STOP_ORDER_EXPIRATION_TYPE_UNSPECIFIED = 'Значение не указано',
  STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_CANCEL = 'Действительно до отмены',
  STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_DATE = 'Действительно до даты снятия',
}
