export enum PortfolioInfoEnum {
  DEPOSIT = 'deposit',
  INCOME = 'income',
  EXPENCE = 'expence',
  COMISSION = 'comissions',
  IN_POSITION = 'inPosition',
  SPARE = 'spare',
  PROFIT = 'profit',
  PROFIT_PCT = 'profitPct',
  FIXED_PROFIT = 'fixedProfit',
  FIXED_SUCCESS_COUNT = 'fixedSuccessCount',
  FIXED_UNSUCCESS_COUNT = 'fixedUnsuccessCount',
  IN_POSITION_PROFIT = 'inPositionProfit',
  IN_POSITION_SUCCESS_COUNT = 'inPositionSuccessCount',
  IN_POSITION_UNSUCCESS_COUNT = 'inPositionUnsuccessCount',
}
